### PR TITLE
fix: fix upload URL and preview image on localhost

### LINKED ISSUE #917: Failed to upload image or file
**Describe the bug**
image

image

### PR DESCRIPTION
**Pull request by AliceLanniste**
close #917 

**plus:**
**bug**
preview after upload image or file:
image

fix:
image

I think it's a better way to assign `process.env.STORAGE_PREFIX` should be depend on env variable

### CODE REVIEW

**Comment by boris-w** [comment]
I don’t understand why 127.0.0.1 needs to be changed to localhost.

**Comment by AliceLanniste** [comment]
when I start up project on local, it will open browser forward address starts with localhost instead of 127.0.0.1. upload api and preview api starts with 127.0.0.1, it causes #917 and preview error.


**fail to preview image**
image
image


so I changed 127.0.0.1 to localhost

**Comment by boris-w** [comment]
> when I start up project on local, it will open browser forward address starts with localhost instead of 127.0.0.1. upload api and preview api starts with 127.0.0.1, it causes #917 and preview error.
> 
> **fail to preview image** image image
> 
> so I changed 127.0.0.1 to localhost

It seems that this is a security self-origin configuration restriction of Next.js. I think it’s enough to set STORAGE_PREFIX to localhost

**Comment by AliceLanniste** [comment]
> It seems that this is a security self-origin configuration restriction of Next.js. I think it’s enough to set STORAGE_PREFIX to localhost

OK, I will revert init_app's commit

**Comment by boris-w** [comment]
> > It seems that this is a security self-origin configuration restriction of Next.js. I think it’s enough to set STORAGE_PREFIX to localhost
> 
> OK, I will revert init_app's commit

The changes related to file upload are also not necessary. We are using frontend direct upload, and it’s not mandatory to use the upload interface in our openapi.

**Review by boris-w — APPROVED** [review]

**Pull request merged**
