### PR TITLE
 add an enviroment option to  disable user self registration

### PR DESCRIPTION
**Pull request by mz0in**
This will add environment option to disable user self registration , this is a simple method that can be triggered after the first run of the application and the owner or admin register him self and then can make sure that only user with valid invitation link is able to sign in , or he can provide another instance that has the user registration allowed.

### CODE REVIEW

**Comment by Nainterceptor** [comment]
Hi, I want this feature too. 
I think that it's better to pass through config layer (like https://github.com/teableio/teable/blob/develop/apps/nestjs-backend/src/configs/base.config.ts).
And .env example file that you're modifying is related to front part of the app.
Do you want to make changes or can I submit another PR ?

**Comment by mz0in** [comment]
> Hi, I want this feature too. I think that it's better to pass through config layer (like [`develop`/apps/nestjs-backend/src/configs/base.config.ts](https://github.com/teableio/teable/blob/develop/apps/nestjs-backend/src/configs/base.config.ts?rgh-link-date=2024-03-19T22%3A11%3A44Z)). And .env example file that you're modifying is related to front part of the app. Do you want to make changes or can I submit another PR ?

hello ,  you can add a new PR , since this PR is not approved yet by the teable team , your approach does the same goal so go on , Thanks

**Comment by tea-artist** [comment]
We are planning Admin-related features and will create a discussion for everyone to preview when we have a draft.

**Comment by tea-artist** [comment]
We released the basic functionality of the Admin panel, You can now disable user registration and create new Spaces here.
image

> Migration tip: you need to find yourself in the database user table and change the is_admin field to true
```sql
UPDATE "public"."users" SET "is_admin" = 't' WHERE "email" = 'your@register.email';
```

> For the newly deployed instance, the first user will become the administrator

**Comment by nicholas-mn** [comment]
> We released the basic functionality of the Admin panel, You can now disable user registration and create new Spaces here. image
> 
> > Migration tip: you need to find yourself in the database user table and change the is_admin field to true
> 
> ```sql
> UPDATE "public"."users" SET "is_admin" = 't' WHERE "email" = 'your@register.email';
> ```
> 
> > For the newly deployed instance, the first user will become the administrator

Step-by-step on how to do this for non-advanced users on an already running docker instance? 🙏

**Comment by tea-artist** [comment]
@mini-mini-oss 
If you're deploying with docker standalone example. You can find the database account information in the `.env` file.

```sh
POSTGRES_DB=_db_name
POSTGRES_USER=_db_user_name_
POSTGRES_PASSWORD=_db_pass_
```
In the following commands, replace the actual value

Find the database container id
```sh
docker ps
```

Entry container (replace with the _container_id_ of the previous step
```sh
docker exec -it _container_id_ bash
```

Login database (replace with the _db_user_, _db_name_, press Enter and you may be asked to enter your password)
```sh
psql -U _db_user_ -d _db_name_
```

Enter SQL to update your administrator account (Be sure to replace email with your registered account)

```sh
UPDATE "public"."users" SET "is_admin" = 't' WHERE "email" = 'your@register.email';
```

If successful, it will be displayed
```sh
UPDATE 1
```

**Comment by nicholas-mn** [comment]
> @mini-mini-oss If you're deploying with docker standalone example. You can find the database account information in the `.env` file.
> 
> ```shell
> POSTGRES_DB=_db_name
> POSTGRES_USER=_db_user_name_
> POSTGRES_PASSWORD=_db_pass_
> ```
> 
> In the following commands, replace the actual value
> 
> Find the database container id
> 
> ```shell
> docker ps
> ```
> 
> Entry container (replace with the _container_id_ of the previous step
> 
> ```shell
> docker exec -it _container_id_ bash
> ```
> 
> Login database (replace with the _db_user_, _db_name_, press Enter and you may be asked to enter your password)
> 
> ```shell
> psql -U _db_user_ -d _db_name_
> ```
> 
> Enter SQL to update your administrator account (Be sure to replace email with your registered account)
> 
> ```shell
> UPDATE "public"."users" SET "is_admin" = 't' WHERE "email" = 'your@register.email';
> ```
> 
> If successful, it will be displayed
> 
> ```shell
> UPDATE 1
> ```

Great, thank you so much!
I will definitely keep an eye on future development - you guys are doing a fantastic job. 😊🙏

**Pull request closed without merging**
